# Generated by Django 6.0.1 on 2026-02-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
    ]
