# Generated by Django 6.0.1 on 2026-02-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=17, verbose_name="Телефон"
            ),
            preserve_default=False,
        ),
    ]
