# Generated by Django 6.0.1 on 2026-04-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_contact_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="name",
            new_name="username",
        ),
    ]
