# Generated by Django 6.0.1 on 2026-06-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_product_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
